# Generated by Django 2.1.4 on 2018-12-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Unnamed Game')),
                ('genre', models.TextField(default='Education')),
                ('plays', models.IntegerField(default=0)),
                ('image', models.TextField(default='')),
                ('code', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('time', models.FloatField(default=0.0)),
                ('score', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('level', models.IntegerField(default=0)),
                ('name', models.TextField(default='Alice')),
                ('phone', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('owned_games', models.ManyToManyField(to='app.Game')),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.User'),
        ),
    ]
